using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace BSerializer.Generator;

internal static class CodeEmitter
{
    public static string Emit(ContextModel model, SourceProductionContext spc)
    {
        var analyzer = new TypeAnalyzer();
        foreach (var rootType in model.RootTypes)
            analyzer.AnalyzeRootType(rootType);

        var types = analyzer.CustomTypes;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.ContextNamespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {model.ContextName} : BSerializer.BSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {model.ContextName} Instance {{ get; }} = new();");
        sb.AppendLine();

        EmitSerializeCore(sb, types);
        EmitDeserializeCore(sb, types);
        EmitWriteSchema(sb, types);
        EmitSkipSchema(sb);

        foreach (var type in types)
        {
            EmitWriteMethod(sb, type);
            EmitReadMethod(sb, type);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSerializeCore(StringBuilder sb, List<TypeInfo> types)
    {
        sb.AppendLine("    protected override byte[] SerializeCore(object obj, Type type)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var stream = new MemoryStream();");
        sb.AppendLine("        using var writer = new BinaryWriter(stream);");
        sb.AppendLine("        WriteSchema(writer);");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullName})) Write_{type.SafeName}(writer, ({type.FullName})obj);");
        }
        sb.AppendLine("        return stream.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitDeserializeCore(StringBuilder sb, List<TypeInfo> types)
    {
        sb.AppendLine("    protected override object DeserializeCore(byte[] data, Type type)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var stream = new MemoryStream(data);");
        sb.AppendLine("        using var reader = new BinaryReader(stream);");
        sb.AppendLine("        SkipSchema(reader);");
        foreach (var type in types)
        {
            sb.AppendLine($"        if (type == typeof({type.FullName})) return Read_{type.SafeName}(reader);");
        }
        sb.AppendLine("        throw new NotSupportedException($\"Type {type} is not registered.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitWriteSchema(StringBuilder sb, List<TypeInfo> types)
    {
        sb.AppendLine("    private static void WriteSchema(BinaryWriter w)");
        sb.AppendLine("    {");
        sb.AppendLine($"        w.Write((uint){types.Count});");
        foreach (var type in types)
        {
            sb.AppendLine($"        w.Write((uint){type.Id}); w.Write(\"{type.FullName}\"); w.Write((uint){type.Properties.Count});");
            foreach (var prop in type.Properties)
                sb.AppendLine($"        w.Write((uint){prop.Id}); w.Write((uint){prop.TypeId}); w.Write(\"{prop.Name}\");");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSkipSchema(StringBuilder sb)
    {
        sb.AppendLine("    private static void SkipSchema(BinaryReader r)");
        sb.AppendLine("    {");
        sb.AppendLine("        var c = r.ReadUInt32(); for (uint i = 0; i < c; i++) { r.ReadUInt32(); r.ReadString(); var pc = r.ReadUInt32(); for (uint j = 0; j < pc; j++) { r.ReadUInt32(); r.ReadUInt32(); r.ReadString(); } }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitWriteMethod(StringBuilder sb, TypeInfo type)
    {
        sb.AppendLine($"    private static void Write_{type.SafeName}(BinaryWriter w, {type.FullName} obj)");
        sb.AppendLine("    {");
        foreach (var prop in type.Properties)
            EmitWriteProp(sb, prop.Type, $"obj.{prop.Name}", "        ");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitWriteProp(StringBuilder sb, ITypeSymbol type, string acc, string ind)
    {
        var cat = TypeAnalyzer.CategorizeType(type);
        var isRef = TypeAnalyzer.IsReferenceType(type);

        if (isRef)
        {
            sb.AppendLine($"{ind}if ({acc} == null) {{ w.Write(false); }} else {{ w.Write(true);");
            EmitWriteVal(sb, type, acc, cat, ind);
            sb.AppendLine($"{ind}}}");
        }
        else
        {
            EmitWriteVal(sb, type, acc, cat, ind);
        }
    }

    private static void EmitWriteVal(StringBuilder sb, ITypeSymbol type, string acc, TypeCategory cat, string ind)
    {
        switch (cat)
        {
            case TypeCategory.Primitive:
                sb.AppendLine($"{ind}w.Write({acc});");
                break;
            case TypeCategory.ByteArray:
                sb.AppendLine($"{ind}w.Write({acc}.Length); w.Write({acc});");
                break;
            case TypeCategory.NullableValue:
                var inner = ((INamedTypeSymbol)type).TypeArguments[0];
                EmitWriteVal(sb, inner, $"{acc}.Value", TypeAnalyzer.CategorizeType(inner), ind);
                break;
            case TypeCategory.Array:
                EmitWriteCollection(sb, ((IArrayTypeSymbol)type).ElementType, acc, ".Length", ind);
                break;
            case TypeCategory.List:
                EmitWriteCollection(sb, ((INamedTypeSymbol)type).TypeArguments[0], acc, ".Count", ind);
                break;
            case TypeCategory.Dictionary:
                var args = ((INamedTypeSymbol)type).TypeArguments;
                sb.AppendLine($"{ind}w.Write({acc}.Count);");
                sb.AppendLine($"{ind}foreach (var _kv in {acc}) {{");
                EmitWriteProp(sb, args[0], "_kv.Key", ind + "    ");
                EmitWriteProp(sb, args[1], "_kv.Value", ind + "    ");
                sb.AppendLine($"{ind}}}");
                break;
            case TypeCategory.CustomObject:
                var safe = SafeName(type);
                sb.AppendLine($"{ind}Write_{safe}(w, {acc});");
                break;
        }
    }

    private static void EmitWriteCollection(StringBuilder sb, ITypeSymbol elemType, string acc, string countProp, string ind)
    {
        sb.AppendLine($"{ind}w.Write({acc}{countProp});");
        sb.AppendLine($"{ind}foreach (var _el in {acc}) {{");
        EmitWriteProp(sb, elemType, "_el", ind + "    ");
        sb.AppendLine($"{ind}}}");
    }

    private static void EmitReadMethod(StringBuilder sb, TypeInfo type)
    {
        sb.AppendLine($"    private static {type.FullName} Read_{type.SafeName}(BinaryReader r)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var obj = new {type.FullName}();");
        foreach (var prop in type.Properties)
        {
            var readExpr = EmitReadExpr(prop.Type, "r");
            var isRef = TypeAnalyzer.IsReferenceType(prop.Type);
            if (isRef)
                sb.AppendLine($"        obj.{prop.Name} = r.ReadBoolean() ? {readExpr} : default;");
            else
                sb.AppendLine($"        obj.{prop.Name} = {readExpr};");
        }
        sb.AppendLine("        return obj;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string EmitReadExpr(ITypeSymbol type, string r)
    {
        var cat = TypeAnalyzer.CategorizeType(type);
        switch (cat)
        {
            case TypeCategory.Primitive:
                return ReadPrimitive(type, r);
            case TypeCategory.ByteArray:
                return $"{r}.ReadBytes({r}.ReadInt32())";
            case TypeCategory.NullableValue:
                var inner = ((INamedTypeSymbol)type).TypeArguments[0];
                return EmitReadExpr(inner, r);
            case TypeCategory.Array:
                var arrElem = ((IArrayTypeSymbol)type).ElementType;
                return EmitReadArrayExpr(arrElem, r);
            case TypeCategory.List:
                var listElem = ((INamedTypeSymbol)type).TypeArguments[0];
                return EmitReadListExpr(listElem, r);
            case TypeCategory.Dictionary:
                var dArgs = ((INamedTypeSymbol)type).TypeArguments;
                return EmitReadDictExpr(dArgs[0], dArgs[1], r);
            case TypeCategory.CustomObject:
                return $"Read_{SafeName(type)}({r})";
            default:
                return "default";
        }
    }

    private static string EmitReadElemExpr(ITypeSymbol type, string r)
    {
        var isRef = TypeAnalyzer.IsReferenceType(type);
        var readExpr = EmitReadExpr(type, r);
        return isRef ? $"({r}.ReadBoolean() ? {readExpr} : default)" : readExpr;
    }

    private static string EmitReadArrayExpr(ITypeSymbol elemType, string r)
    {
        var elemName = elemType.ToDisplayString();
        var readElem = EmitReadElemExpr(elemType, "ra");
        return $"((Func<BinaryReader, {elemName}[]>)(ra => {{ var c = ra.ReadInt32(); var a = new {elemName}[c]; for (var i = 0; i < c; i++) a[i] = {readElem}; return a; }}))({r})";
    }

    private static string EmitReadListExpr(ITypeSymbol elemType, string r)
    {
        var elemName = elemType.ToDisplayString();
        var readElem = EmitReadElemExpr(elemType, "rl");
        return $"((Func<BinaryReader, List<{elemName}>>)(rl => {{ var c = rl.ReadInt32(); var l = new List<{elemName}>(c); for (var i = 0; i < c; i++) l.Add({readElem}); return l; }}))({r})";
    }

    private static string EmitReadDictExpr(ITypeSymbol keyType, ITypeSymbol valType, string r)
    {
        var keyName = keyType.ToDisplayString();
        var valName = valType.ToDisplayString();
        var readKey = EmitReadElemExpr(keyType, "rd");
        var readVal = EmitReadElemExpr(valType, "rd");
        return $"((Func<BinaryReader, Dictionary<{keyName}, {valName}>>)(rd => {{ var c = rd.ReadInt32(); var d = new Dictionary<{keyName}, {valName}>(c); for (var i = 0; i < c; i++) d.Add({readKey}, {readVal}); return d; }}))({r})";
    }

    private static string ReadPrimitive(ITypeSymbol type, string r)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Boolean => $"{r}.ReadBoolean()",
            SpecialType.System_Byte => $"{r}.ReadByte()",
            SpecialType.System_SByte => $"{r}.ReadSByte()",
            SpecialType.System_Int16 => $"{r}.ReadInt16()",
            SpecialType.System_UInt16 => $"{r}.ReadUInt16()",
            SpecialType.System_Int32 => $"{r}.ReadInt32()",
            SpecialType.System_UInt32 => $"{r}.ReadUInt32()",
            SpecialType.System_Int64 => $"{r}.ReadInt64()",
            SpecialType.System_UInt64 => $"{r}.ReadUInt64()",
            SpecialType.System_Single => $"{r}.ReadSingle()",
            SpecialType.System_Double => $"{r}.ReadDouble()",
            SpecialType.System_Decimal => $"{r}.ReadDecimal()",
            SpecialType.System_Char => $"{r}.ReadChar()",
            SpecialType.System_String => $"{r}.ReadString()",
            _ => "default"
        };
    }

    private static string SafeName(ITypeSymbol type)
    {
        return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString()
            .Replace(".", "_").Replace("<", "_").Replace(">", "_")
            .Replace(",", "_").Replace(" ", "").Replace("?", "");
    }
}
